version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nodeApp
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:        
  ApplicationStop:
    - location: scripts/stopServer.sh
    
  ApplicationStart:
    - location: scripts/startServer.sh
  
  ValidateService:
    - location: scripts/validate.sh
