version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
file_exists_behavior: OVERWRITE


hooks:

  ApplicationStop:
    - location: scripts/stopServer.sh 

  ApplicationStart:
    - location: scripts/startServer.sh
