version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:    
  ApplicationStart:
    - location: scripts/startServer.sh
  
  ValidateService:
    - location: scripts/validate.sh
