version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stopServer.sh
    
  ApplicationStart:
    - location: scripts/startServer.sh
  
  ValidateService:
    - location: scripts/validate.sh
