version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStart:
    - location: scripts/startServer.sh
  
  ValidateService:
    - location: scripts/validate.sh
