version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:    
    commands:
      - sudo apt update
      - sudo npm install pm2 -g
      - sudo apt install jq -y
      - MONGODB_URI=$(aws ssm get-parameters --name /aryan/db_replicaset_url --with-decryption --query "Parameters[0]" | jq -r .Value)
      - SECRET=$(aws ssm get-parameters --name /aryan/jwt/secret --with-decryption --query "Parameters[0]" | jq -r .Value)
      - PORT=$(aws ssm get-parameters --name /aryan/nodejs/port  --query "Parameters[0]" | jq -r .Value)
      - NODE_ENV=$(aws ssm get-parameters --name /aryan/nodejs/env  --query "Parameters[0]" | jq -r .Value)
      - echo $MONGODB_URI $SECRET $PORT $NODE_ENV
      - npm install 
      - npm install dotenv      
      

  build:
    commands:
      - echo "MONGODB_URI=$MONGODB_URI" > .env
      - echo "SECRET=$SECRET" >> .env
      - echo "PORT=$PORT" >> .env
      - echo "NODE_ENV=$NODE_ENV" >> .env
      - echo Build Completed on `date`
  post_build:
    commands:
      - cat app.js
      - pm2 start app.js
      - echo `curl localhost:5000/`
      - echo `curl localhost:5000/api/tags`
      - cat ~/.pm2/logs/app-out.log
      - pm2 stop 0
      - pm2 delete 0
      - echo Congratulations!!!!!


artifacts:
  files:
    - '**/*'
